module AdminModel
{
    class LibraryGet
    {
        Array String path
    }

    class LibraryPut
    {
        Array String path
    }

    class LibraryResponse
    {
        Array LibraryItemFile files
        Array LibraryItemDirectory directories
    }

    class LibraryItemFile
    {
        String name
        Array String checksums
    }

    class LibraryItemDirectory
    {
        String name
    }

    class LogGet
    {
    }

    class LogDelete
    {
        UInt64 count
    }

    class Log
    {
        Array Object log
    }

    class ProcessIndexRequest
    {
        Array String path
    }

    class ProcessIndexResult
    {
        Array String path
        String sha256sum
    }

    class ProcessIndexProblem
    {
        Array String path
        String reason
    }

    class RemoteError
    {
        String message
    }
}
////1
