module AdminModel
{
    class IndexListGet
    {
    }

    class IndexListResponse
    {
        Hash String LibraryIndex list_index
    }

    class IndexGet
    {
        String sha256sum
    }

    // LibraryIndex is used as IndexResponse

    class LibraryGet
    {
        Array String path
    }

    class LibraryPut
    {
        Array String path
    }

    class LibraryResponse
    {
        Array LibraryItemFile files
        Array LibraryItemDirectory directories
    }

    class LibraryItemFile
    {
        String name
        Array String checksums
    }

    class LibraryItemDirectory
    {
        String name
    }

    class LogGet
    {
    }

    class LogDelete
    {
        UInt64 count
    }

    class Log
    {
        Array Object log
    }

    class CheckMediaResult
    {
        Array String path
    }

    class CheckMediaError
    {
        Array String path
        String reason
    }

    class CheckMediaWarning
    {
        Array String path
        String reason
    }

    class MediaSequence
    {
        Array MediaFrame frames
    }
    class MediaFrame
    {
        UInt64 count
        String uri
    }
    class MediaDefinition
    {
        Array MediaTypeDefinition types_definitions
    }
    class MediaTypeDefinition
    {
        Object type // MediaTypeDescriptionVideoContainer
        MediaSequence sequence
    }

    class MediaTypeDescriptionAVStreamTranscode
    {
        String codec
        String codec_priv_key
        String codec_priv_value
        Object filter// MediaTypeDescriptionVideoFilter
    }

    class MediaTypeDescriptionVideoFilter
    {
        UInt64 height
        UInt64 width
        UInt64 fps
    }

    class MediaTypeDescriptionAVStream
    {
        Object transcode// MediaTypeDescriptionAVStreamTranscode
    }

    class MediaTypeDescriptionVideoContainer
    {
        Object audio// MediaTypeDescriptionAVStream
        Object video// MediaTypeDescriptionAVStream

        String muxer_opt_key
        String muxer_opt_value
        String container_extension
    }

    class LibraryIndex
    {
        Set String paths
        MediaDefinition media_definition
    }

    class RemoteError
    {
        String message
    }
}
////2
