module InternalModel
{
    ///
    //  stored in filesystem
    ///
    class LibraryTree
    {
        Optional Set String names
        Optional String checksum
    }

    class PendingForIndexItem
    {
        String sha256sum
        Array String path
        Set String type_descriptions
    }
    class PendingForIndex
    {
        Array PendingForIndexItem items
    }

    class PendingForMediaCheck
    {
        Array ProcessMediaCheckRequest items
    }

    class ProcessMediaCheckRequest
    {
        Array String path
        String output_dir

        // value can be MediaTypeDescriptionVideoContainer serialized
        Set String type_descriptions
    }

    ///
    ///

    class ProcessIndexRequest
    {
        Array String path
        Set String type_descriptions
    }

    class ProcessIndexResult
    {
        Array String path
        String sha256sum
        Set String type_descriptions
    }

    class ProcessIndexError
    {
        Array String path
        Set String type_descriptions
        String reason
    }

    class ProcessMediaCheckResult
    {
        UInt64 accumulated
        UInt64 count
        Array String path
        Extension type_description // MediaTypeDescriptionVideoContainer
        String data_or_file
        ResultType result_type
    }
    enum ResultType {data file}
}
////2
