module InternalModel
{
    ///
    //  stored in filesystem
    ///
    class LibraryTree
    {
        Set String names
        Set String checksums
    }

    class PendingForIndexItem
    {
        String sha256sum
        Array String path
    }
    class PendingForIndex
    {
        Array PendingForIndexItem items
    }

    class PendingForMediaCheck
    {
        Array ProcessMediaCheckRequest items
    }

    class ProcessMediaCheckRequest
    {
        Array String path
        String output_dir

        // value can be MediaTypeDescriptionVideo serialized
        Set String types_definitions
    }

    ///
    ///

    class ProcessIndexRequest
    {
        Array String path
    }

    class ProcessIndexResult
    {
        Array String path
        String sha256sum
    }

    class ProcessMediaCheckResult
    {
        UInt64 accumulated
        UInt64 count
        Array String path
        Extension type // MediaTypeDescriptionVideo
        String data_or_file
        ResultType result_type
    }
    enum ResultType {data file}

    class AdminModelWrapper
    {
        Extension package
    }

    ///
    // these interface with storage api
    ///
    class StorageOrder
    {
        String storage_address
        String file_uri
        String content_unit_uri
        String session_id
        UInt64 seconds
        TimePoint time_point
    }

    class SignedStorageOrder
    {
        StorageOrder order
        Authority authorization
    }

    class Authority
    {
        String address
        String signature
    }
}
////2
